apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: f19tbg1ty-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/rhtap-qe:54be6f5d4be9a84f93b6bc261024f25b7f9a0f83@sha256:d8a505028f0e3b7c0beacfdc166fd332734ff5144062f674aef8b47e8a823987
        name: container-image  
